### ISSUE TITLE
github version only shows a window with tabs no mounts 

### ISSUE THREAD

**Issue by grilor** [Camyana/MCL#1]
here is the error from BugSack:

1x Interface/AddOns/MCL/functions.lua:329: attempt to index field 'overview' (a nil value)
[string "@Interface/AddOns/MCL/functions.lua"]:329: in function `UpdateCollection'
[string "@Interface/AddOns/MCL/main.lua"]:73: in function `Toggle'
[string "@Interface/AddOns/MCL/Core.lua"]:17: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4924: in function <Interface/FrameXML/ChatFrame.lua:4920>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
self = <table> {
 UpdateCollection = <function> defined @Interface/AddOns/MCL/functions.lua:276
 LinkMountItem = <function> defined @Interface/AddOns/MCL/functions.lua:115
 TableMounts = <function> defined @Interface/AddOns/MCL/functions.lua:24
 getTableLength = <function> defined @Interface/AddOns/MCL/functions.lua:107
 CreateMountsForCategory = <function> defined @Interface/AddOns/MCL/functions.lua:180
 GetMountID = <function> defined @Interface/AddOns/MCL/functions.lua:234
 getFaction = <function> defined @Interface/AddOns/MCL/functions.lua:11
 CreateBorder = <function> defined @Interface/AddOns/MCL/functions.lua:93
 initSections = <function> defined @Interface/AddOns/MCL/functions.lua:34
 TestFunction = <function> defined @Interface/AddOns/MCL/functions.lua:103
}
(*temporary) = <function> defined @Interface/AddOns/MCL/functions.lua:254
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'overview' (a nil value)"
clearOverviewStats = <function> defined @Interface/AddOns/MCL/functions.lua:270
core = <table> {
 MCL_MF_Nav = Nav {
 }
 stats = <table> {
 }
 MCL_MF = MCLFrame {
 }
 sectionNames = <table> {
 }
 overviewStats = <table> {
 }
 Frames = <table> {
 }
 collected = 0
 mounts = <table> {
 }
 total = 0
 Main = <table> {
 }
 sectionFrames = <table> {
 }
 sections = <table> {
 }
 overviewFrames = <table> {
 }
 Function = <table> {
 }
 mountList = <table> {
 }
}

**Comment by Camyana** [comment]
New version released that fixes this issue on initialising the addon.

**Comment by grilor** [comment]
Got it thanks. Love the addon
