### ISSUE TITLE
Installed from Curse, does not work when running no other addons

### ISSUE THREAD

**Issue by RudolphRiedel** [Camyana/MCL#2]
When disabling all other addons I get this:
Message: Interface/AddOns/MCL/functions.lua:923: Cannot find a library instance of "AceConfig-3.0".
Time: Fri Nov 25 20:48:37 2022
Count: 1
Stack: Interface/AddOns/MCL/functions.lua:923: Cannot find a library instance of "AceConfig-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/MCL/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/MCL/functions.lua"]:923: in function `AddonSettings'
[string "@Interface/AddOns/MCL/main.lua"]:89: in function <Interface/AddOns/MCL/main.lua:81>

Locals: (*temporary) = "Cannot find a library instance of "AceConfig-3.0"."

The embedded ACE3 lib appears to be incomplete.

**Comment by Camyana** [comment]
AceConfig was missing, thank you.

Pushed a new update to include the library.

**Comment by RudolphRiedel** [comment]
Just installed v2.1.2, adding AceConfig does not fix it, now LibSharedMedia is missing:

Message: Interface/AddOns/MCL/functions.lua:923: Cannot find a library instance of "LibSharedMedia-3.0".
Time: Sat Nov 26 18:48:48 2022
Count: 1
Stack: Interface/AddOns/MCL/functions.lua:923: Cannot find a library instance of "LibSharedMedia-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/MCL/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/MCL/functions.lua"]:923: in function `AddonSettings'
[string "@Interface/AddOns/MCL/main.lua"]:89: in function <Interface/AddOns/MCL/main.lua:81>

Locals: (*temporary) = "Cannot find a library instance of "LibSharedMedia-3.0"."

I tried to fix this myself yesterday to be more helpfull but instead of one LUA error less I got four instead. :-)
It works when I enable all my other addons, probably because something else already is loading ACE3.
But I only have a select few addons on a second computer and this is why I test with everything else disabled.

**Comment by Camyana** [comment]
Ha, okay I see why I'm not getting that error. I'm using bugsack which has these libraries built in.

Ironic that an addon designed to show you lua errors is preventing them from happening.

Just released a fixed version, thanks for the report.

**Comment by RudolphRiedel** [comment]
Oh, nice, that explains why it works on my machine with everything on as this includes BugSack as well. :-)
I will try it out again when it appears in WowUp.

**Comment by RudolphRiedel** [comment]
I works now with everything else switch off, nice. :-)

One odd thing though I just noticed now, the minimap button is on the wrong position with all other addons switched off.
![grafik](https://user-images.githubusercontent.com/31180093/204108689-59d25d3b-2457-479d-85ef-b5428b8e7fd9.png)
![grafik](https://user-images.githubusercontent.com/31180093/204108697-be9609c2-539f-4726-9e18-a6175e6a57a8.png)
