### ISSUE TITLE
Feature/Revisions request

### ISSUE THREAD

**Issue by ghost** [Camyana/MCL#4]
First of all, thank you for amazing addon :)

Some things I would like to see improved:

1) Minimap icon - I would like to have tooltip text with name of addon (similar to all other addons usually)
Reason being icons are quite small, sometimes with quick glance i rely on the tooltip text to make sure im clicking the right button! (I have sooo many). Should be an easy fix i hope!
![image](https://user-images.githubusercontent.com/122007087/236599134-b543c70a-ecad-499a-aa0d-56adc58c4112.png)

2) On login, i have to click 2-4 times on minimap button just to open the addon. (I assume because it loads all the info).
Is it possible to instead open addon on 1st click - but perhaps grey out the window area until it fully loads? Perhaps even with a loading bar if it makes sense?
Reason being users often click once and move cursor away from map (or in my case use addons as button bag). It can get so annoying realising i need to open the button bag again, and try again! Please consider this :)

3) Minor thing but i would like blizzard style frame. (instead of the current black with transparency).
Perhaps it can be an optional skin? I think it would fit very nicely :)

Thank you!!

**Comment by Camyana** [comment]
Suggestion 1 and 2 are complete.

Suggestion 3, I'll think about in the future as it's a slightly bigger task.
